// Test generated by RoostGPT for test aa using AI Type Open AI and AI Model gpt-4

package main

import (
	"fmt"
	"testing"
)

type Shape struct {
	area float64
}

func (sq *Shape) Area() float64 {
	fmt.Println("Calling Shape Area")
	return sq.area //return area of square
}

func TestArea_2deee0bdb2(t *testing.T) {
	t.Run("Area with positive value", func(t *testing.T) {
		sq := &Shape{area: 25.0}
		got := sq.Area()
		want := 25.0

		if got != want {
			t.Errorf("got %.2f want %.2f", got, want)
		}
	})

	t.Run("Area with zero value", func(t *testing.T) {
		sq := &Shape{area: 0.0}
		got := sq.Area()
		want := 0.0

		if got != want {
			t.Errorf("got %.2f want %.2f", got, want)
		}
	})

	t.Run("Area with negative value", func(t *testing.T) {
		sq := &Shape{area: -25.0}
		got := sq.Area()
		want := -25.0

		if got != want {
			t.Errorf("got %.2f want %.2f", got, want)
		}
	})
}
