// Test generated by RoostGPT for test roost-go using AI Type Open AI and AI Model gpt-4

package main

import (
	"testing"
)

type Square struct {
	side float64
	area float64
}

func (sq *Square) CalculateArea() {
	sq.area = sq.side * sq.side //area of square
}

func TestCalculateArea_d01053d701(t *testing.T) {

	sq := &Square{side: 5.0}
	sq.CalculateArea()
	if sq.area != 25.0 {
		t.Errorf("Expected area of square with side 5.0 to be 25.0, but got %f", sq.area)
	}

	sq = &Square{side: 0.0}
	sq.CalculateArea()
	if sq.area != 0.0 {
		t.Errorf("Expected area of square with side 0.0 to be 0.0, but got %f", sq.area)
	}

	sq = &Square{side: -5.0}
	sq.CalculateArea()
	if sq.area != 25.0 {
		t.Errorf("Expected area of square with side -5.0 to be 25.0, but got %f", sq.area)
	}
}
