// Test generated by RoostGPT for test aa using AI Type Open AI and AI Model gpt-4

package main

import (
	"testing"
)

type Rectangle struct {
	width, height float64
}

func (rect *Rectangle) CalculateArea() float64 {
	return rect.width * rect.height //area of rectangle
}

func TestCalculateArea_5309603980(t *testing.T) {
	// Test case 1: Positive numbers
	rect1 := Rectangle{width: 5, height: 6}
	area1 := rect1.CalculateArea()
	if area1 != 30 {
		t.Errorf("Failed! Expected area: %f, but got: %f", 30.0, area1)
	}

	// Test case 2: Zero value
	rect2 := Rectangle{width: 0, height: 6}
	area2 := rect2.CalculateArea()
	if area2 != 0 {
		t.Errorf("Failed! Expected area: %f, but got: %f", 0.0, area2)
	}

	// Test case 3: Negative numbers
	rect3 := Rectangle{width: -5, height: 6}
	area3 := rect3.CalculateArea()
	if area3 != -30 {
		t.Errorf("Failed! Expected area: %f, but got: %f", -30.0, area3)
	}

	// Test case 4: Floating point numbers
	rect4 := Rectangle{width: 5.5, height: 6.5}
	area4 := rect4.CalculateArea()
	if area4 != 35.75 {
		t.Errorf("Failed! Expected area: %f, but got: %f", 35.75, area4)
	}
}
