// Test generated by RoostGPT for test simple-go using AI Model gpt

package main

import (
	"testing"
)

type Rectangle struct {
	width  float64
	height float64
}

func (rect Rectangle) CalculateArea() float64 {
	return rect.width * rect.height //area of rectangle
}

func TestCalculateAreaacb586a213(t *testing.T) {
	rect1 := Rectangle{width: 5, height: 4}
	area1 := rect1.CalculateArea()
	if area1 != 20 {
		t.Error("Test case 1 failed: expected 20, got ", area1)
	}

	rect2 := Rectangle{width: 0, height: 0}
	area2 := rect2.CalculateArea()
	if area2 != 0 {
		t.Error("Test case 2 failed: expected 0, got ", area2)
	}

	rect3 := Rectangle{width: -3, height: 4}
	area3 := rect3.CalculateArea()
	if area3 != -12 {
		t.Error("Test case 3 failed: expected -12, got ", area3)
	}
}
