// Test generated by RoostGPT for test simple-go using AI Model gpt

package main

import (
	"testing"
)

type Shape struct {
	area float64
}

func (sq *Shape) Area() float64 {
	return sq.area //return area of square
}

func TestArea7903ff2d66(t *testing.T) {
	// Test case 1: Positive scenario
	shape1 := &Shape{area: 25.0}
	if shape1.Area() != 25.0 {
		t.Error("Expected area of shape1 to be 25.0, but got ", shape1.Area())
	}

	// Test case 2: Zero area scenario
	shape2 := &Shape{area: 0.0}
	if shape2.Area() != 0.0 {
		t.Error("Expected area of shape2 to be 0.0, but got ", shape2.Area())
	}

	// Test case 3: Negative scenario
	shape3 := &Shape{area: -5.0}
	if shape3.Area() != -5.0 {
		t.Error("Expected area of shape3 to be -5.0, but got ", shape3.Area())
	}
}
